### ISSUE TITLE
Looks like they dropped a new captcha

### ISSUE THREAD

**Issue by slabodan** [drunohazarb/4chan-captcha-solver#15] opened 2024-01-12 11:54 UTC
4 letters in this one 

<img width="221" alt="Screenshot 2024-01-12 at 13 51 30" src="https://github.com/drunohazarb/4chan-captcha-solver/assets/101034961/1997f26d-70b7-47ba-9e50-7e88622e8740">

<img width="245" alt="Screenshot 2024-01-12 at 13 53 20" src="https://github.com/drunohazarb/4chan-captcha-solver/assets/101034961/1b3225a1-6d3e-485f-8e5d-f6d918f8c0ca">

**Comment by JonseyJones** [comment] 2024-01-12 14:55
I can confirm.
![Screenshot 2024-01-12 at 16-54-39 (42) _g_ - The new glowie captcha doesn't work on Firefox any - Technology - 4chan](https://github.com/drunohazarb/4chan-captcha-solver/assets/35809877/e8239df3-9eb9-4d14-834d-0ba6b257ad17)

**Comment by wewlad-dev** [comment] 2024-01-12 16:37
Yeah I came to post that the new trained model isn't accurate, turned out they have a new captcha.. I guess glowies are monitoring this repository for any new update and they immediately activate the new captcha as soon as a new solver script is released to render these solvers useless.
![Screenshot_20240112_113201](https://github.com/drunohazarb/4chan-captcha-solver/assets/59626410/cd399426-b1fd-43c2-9497-c8114beec4d9)
![Screenshot_20240112_113225](https://github.com/drunohazarb/4chan-captcha-solver/assets/59626410/3ee7248f-d914-410c-94a6-dfe617ecf7d9)
![Screenshot_20240112_113255](https://github.com/drunohazarb/4chan-captcha-solver/assets/59626410/308d0ff2-76f1-4d77-918b-41ece4977e05)

**Comment by JonseyJones** [comment] 2024-01-12 16:58
> Yeah I came to post that the new trained model isn't accurate, turned out they have a new captcha.. I guess glowies are monitoring this repository for any new update and they immediately activate the new captcha as soon as a new solver script is released to render these solvers useless. ![Screenshot_20240112_113201](https://private-user-images.githubusercontent.com/59626410/296302501-cd399426-b1fd-43c2-9497-c8114beec4d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzg5MDcsIm5iZiI6MTcwNTA3ODYwNywicGF0aCI6Ii81OTYyNjQxMC8yOTYzMDI1MDEtY2QzOTk0MjYtYjFmZC00M2MyLTk0OTctYzgxMTRiZWVjNGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE2NTY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzY2JhNzI3YmJlZjA5ODBjZTRhZjMwNjBkZjY5M2U1MWQ2YjQ2ZTQ3MmFmZDJhMzE1MmI3MGMzZDFmNWZhOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YVmgWsym28fFalbcRw2hQwt453YLwVUa99IyuWIiNc4) ![Screenshot_20240112_113225](https://private-user-images.githubusercontent.com/59626410/296302504-3ee7248f-d914-410c-94a6-dfe617ecf7d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzg5MDcsIm5iZiI6MTcwNTA3ODYwNywicGF0aCI6Ii81OTYyNjQxMC8yOTYzMDI1MDQtM2VlNzI0OGYtZDkxNC00MTBjLTk0YTYtZGZlNjE3ZWNmN2Q5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE2NTY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyZDUxMGIyNzNjMGM1MThkNDUzYThmZDljMmZiNWZmMTI3ZWM0ZDQ3MTE3NTM4ZGI0NjUxYWZmNmY1NzkxYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gNOVEtKG3YC1BmAOZM2JIL4O21OL2hAZGr65-RfabmU) ![Screenshot_20240112_113255](https://private-user-images.githubusercontent.com/59626410/296302508-308d0ff2-76f1-4d77-918b-41ece4977e05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzg5MDcsIm5iZiI6MTcwNTA3ODYwNywicGF0aCI6Ii81OTYyNjQxMC8yOTYzMDI1MDgtMzA4ZDBmZjItNzZmMS00ZDc3LTkxOGItNDFlY2U0OTc3ZTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE2NTY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyMWYwMWYyMDMwOGY4ZGU5YWM3ZjhiMTFhOGJlOTk4ZmY0NGJjYmQ2MWJiMGNhYmM2ZWYwYTIxZWY5NjQyNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XjhmDGGzdUD9XHMgePKqBJ3t16oSCp9vSpXnxjq7NEE)

Most of the times one letter gets repeated and other times it adds a letter that just isn't there and fewer times  a whole lot of wrong letters.

**Comment by HairyMilkshakes** [comment] 2024-01-12 17:44
lol machine learning will defeat it in 1 day, not really an issue.

**Comment by SDBaker88** [comment] 2024-01-12 18:35
It seems to me like they're trying to add different levels of difficulty depending on IP or solving-history kind of like reCAPTCHA, where you get harder ones at first and then progress to easier ones as you solve more and more of the hard ones. I'm only getting 4 letters at the beginning of the session and then it's back to 5 with no black circle.

**Comment by wewlad-dev** [comment] 2024-01-12 18:38
> It seems to me like they're trying to add different levels of difficulty depending on IP or solving-history kind of like reCAPTCHA, where you get harder ones at first and then progress to easier ones as you solve more and more of the hard ones. I'm only getting 4 letters at the beginning of the session and then it's back to 5 with no black circle.

I noticed that and also I noticed it's different based on the board too, some slow boards you get the easy ones from the get go

**Comment by JonseyJones** [comment] 2024-01-12 19:07
> It seems to me like they're trying to add different levels of difficulty depending on IP or solving-history kind of like reCAPTCHA, where you get harder ones at first and then progress to easier ones as you solve more and more of the hard ones. I'm only getting 4 letters at the beginning of the session and then it's back to 5 with no black circle.

You get newer types of captcha first not based on IP but based on the cookie, I think, at first you get the newer 4 letter ones, later 5, clear the cookie and you're back to 4.
I think it's based on the time you spend on the site after you complete the first captcha, after a while it'll revert to the old 5 letter one.
Same happened with the white on black, later on it reverted to black letters on the black blob.

**Comment by aaafre4** [comment] 2024-01-13 00:16
@moffatman can you kindly redeem some captchas please

**Comment by moffatman** [comment] 2024-01-13 00:22
I dont have so many 4 letters ones yet, it seems chance users get them, but not kuroba.... And chance started getting white-letters-on-black-oval a few weeks ago before other people too....

I'll post a zip in a few days once there are enough of each variation you can produce a useful model

**Comment by aaafre4** [comment] 2024-01-13 00:23
thanks m8

**Comment by wewlad-dev** [comment] 2024-01-13 02:36
> You get newer types of captcha first not based on IP but based on the cookie

I don't think that's the case, I have switched several IPs while having the same tab opened, and with the new IP it usually goes like this
- Clouflare captcha
- New 4chan captcha
- old 4chan captcha

And I did try the same IP in a private window, closing it, and trying again after wiping out cookies, I didn't have the new captchas or the cloudflare. I think there's a simple algo somewhere in cloudflare worker that checks the IP if new or spamming or maybe an active board, then it throws the CF captcha, then the new ones.

**Comment by gir489returns** [comment] 2024-01-15 03:37
> And I did try the same IP in a private window, closing it, and trying again after wiping out cookies, I didn't have the new captchas or the cloudflare. I think there's a simple algo somewhere in cloudflare worker that checks the IP if new or spamming or maybe an active board, then it throws the CF captcha, then the new ones.

I was the Nikocado /v/ coin slot spammer for a while. They employ several techniques to fingerprint your browser. While I don't think their automated Cloudflare system is employing the following techniques, it isn't too farfetched that they probably got it from Cloudflare in the first place.

The biggest method they use to determine "repeat offenders" is [browser fingerprinting](https://coveryourtracks.eff.org/). They send a lot of information about your browser back to the server. If you refuse or give fake data, it will give you a CAPTCHA and no matter how well you solve it, it will just keep saying something went wrong with the CAPTCHA.

Another method is file fingerprinting, which works the same way. I think they use AI or something similar to determine variations of the file. While posting the coinslot, I was changing the value of a random pixel by RBG plus or minus 1, and while a human can't tell, that changes the MD5 entirely, at least enough to bypass simple image bans. Once they realized I was using it as an attack, they escalated it to the AI which determines if the image is the same. They probably don't do it that much because it requires a human to train it and I guess when you're doing it for free, you want to do as little work as possible.

Fuck jannies.

**Comment by JonseyJones** [comment] 2024-01-17 11:41
> I'll post a zip in a few days once there are enough of each variation you can produce a useful model
Is the zip ready?

**Comment by moffatman** [comment] 2024-01-17 13:32
@JonseyJones 

https://captcha.chance.surf/bundle_jan17.zip

Still not so many 4-letters ones...

**Comment by aaafre4** [comment] 2024-01-17 13:46
> @JonseyJones
> 
> https://captcha.chance.surf/bundle_jan17.zip
> 
> Still not so many 4-letters ones...

huh if my chatgpt generated command for getting 4 letter filenames in a folder is not lying its only 30? im currently getting only 4 letter ones. could it be that they are not sending 4 letter captchas to phone users then? might need to go on a farming session myself.

**Comment by JonseyJones** [comment] 2024-01-17 17:08
> im currently getting only 4 letter ones.

Start collecting, those are what we miss right now.

**Comment by Yukariin** [comment] 2024-01-17 20:23
Fine-tuned on the new data, achives 4315/4472 (96.4893%) accuracy on this split, or 8503/8724 (97.4668%) on combined dataset (17k new captchas+15k old captchas (without circles))
[model](https://files.catbox.moe/3wv2nl.h5)

A lot of misaligned captchas...

**Comment by JonseyJones** [comment] 2024-01-18 12:05
@drunohazarb is the script ready?

**Comment by drunohazarb** [comment] 2024-01-18 13:01
Yes, but the model is still pretty bad at solving the 4 letter captchas. Only got 8 of 40 captchas right so far. Still better than what we had, I will likely still push the update once I can confirm we don't have any regressions with the other captcha types.

**Comment by gir489returns** [comment] 2024-01-18 17:28
> Yes, but the model is still pretty bad at solving the 4 letter captchas. Only got 8 out of 40 captchas right so far. Still better than what we had, I will likely still push the update once I can confirm we don't have any regressions with the other captcha types.

Food for thought as a red teamer. Their next logical move they could do is permeate the circle. For example, the characters used to be black inside the circle, they could switch back that. What I would do is take the samples for the 5 and 4 characters, invert the colors, and see if the model can still solve it. They're probably gonna keep doing this goalpost shifting shit until one of you capitulates.

**Comment by drunohazarb** [comment] 2024-01-18 20:54
6939964da945d206c9db771d836e828c56a9e0c6

**Comment by BenderBRod** [comment] 2024-01-19 05:16
> [6939964](https://github.com/drunohazarb/4chan-captcha-solver/commit/6939964da945d206c9db771d836e828c56a9e0c6)

the update doesnt change anything for me
it still adds a letter to every captcha

but maybe you shouldnt make public releases anymore since they always changed the captcha 1 hour later

**Comment by aaafre4** [comment] 2024-01-19 05:57
Another solution would be to just add captcha collection into the script, last time 1k captchas was enough to get a good enough model. I've got 210 just from posting as I usually do for the past week. I can try coding something up that doesn't require hosting.

**Comment by aaafre4** [comment] 2024-01-19 09:50
here it is 
https://gist.github.com/aaafre4/55f8438e217a90a5ca5016fa6a75ae6b
https://github.com/drunohazarb/4chan-captcha-solver/assets/156275726/4e05bcbb-e8b4-4f60-8f59-98a5fd125135

**Comment by JonseyJones** [comment] 2024-01-19 13:15
> [6939964](https://github.com/drunohazarb/4chan-captcha-solver/commit/6939964da945d206c9db771d836e828c56a9e0c6)

Adds a letter though.

**Comment by gir489returns** [comment] 2024-01-19 15:16
> [6939964](https://github.com/drunohazarb/4chan-captcha-solver/commit/6939964da945d206c9db771d836e828c56a9e0c6)

Still has problems with the CAPTCHA, it thinks it's a 5 letter when it's a 4 letter.

**Comment by JonseyJones** [comment] 2024-01-19 15:49
>   I've got 210 just from posting as I usually do for the past week. I can try coding something up that doesn't require hosting.
 @aaafre4 
Post them here, apparently the new model was based on only has 30.

**Comment by aaafre4** [comment] 2024-01-19 22:44
what's the point of posting 200 captchas? I will post when I have 1k or when I have the missing amount to 1k. its time for everyone who wants this script to work to stop sitting with their dicks tucked between their legs waiting for something to happen and start collecting captchas

**Comment by JonseyJones** [comment] 2024-01-20 06:31
> what's the point of posting 200 captchas? I will post when I have 1k or when I have the missing amount to 1k. its time for everyone who wants this script to work to stop sitting with their dicks tucked between their legs waiting for something to happen and start collecting captchas

The script saves the captcha after  you post I want it to save the captcha  after it solves it.
@aaafre4  can you make it happen?

**Comment by aaafre4** [comment] 2024-01-20 06:41
I can but why. It will most likely save them with an incorrect label so you will just end up having a bunch of mislabeled captchas also save after post guarantees that it is correct if you plan on fixing them later manually. its double work without guarantee of correctness.

**Comment by aaafre4** [comment] 2024-01-20 06:50
If you can't think of things to post, my suicide bomber captcha farming technique is going to /bant/ where they have 15 sec post cooldowns, pick some random thread and paste this in the console to get a random string in the qr
```
function generateRandomString(length) {
    var result = '';
    var characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    var charactersLength = characters.length;
    for (var i = 0; i < length; i++) {
        result += characters.charAt(Math.floor(Math.random() * charactersLength));
    }
    return result;
}

function setRandomString() {
    var element = document.querySelector("#qr textarea");
    if (element) {
        element.value = generateRandomString(16);
    }
}

setInterval(setRandomString, 3000);
```

and then just solve captchas, since its a 15 sec cooldown you can theoretically get 240 captchas per hour but realistically its half that

**Comment by JonseyJones** [comment] 2024-01-20 08:35
> I can but why. It will most likely save them with an incorrect label so you will just end up having a bunch of mislabeled captchas also save after post guarantees that it is correct if you plan on fixing them later manually. its double work without guarantee of correctness.

I meant to click on "Save"  after you correct it/type it in.

**Comment by aaafre4** [comment] 2024-01-21 07:57
[1k.zip](https://github.com/drunohazarb/4chan-captcha-solver/files/14000496/1k.zip)

cc @Yukariin

**Comment by Yukariin** [comment] 2024-01-21 13:18
That's the best I was able to get with this amount of data. Accuracy 834/1000 (83.4000%) on new data split, 14570/14810 (98.3795%) on combined data dataset.
[model](https://files.catbox.moe/qn52dy.h5)

**Comment by aaafre4** [comment] 2024-01-21 14:11
It's good. It got 17 of 20 captchas right in my test. @drunohazarb when you merge please add my save captcha thing. 

I will try get another 1k captchas but other than that see you all next week (or maybe even tomorrow) in a new issue when they drop the next captcha.

**Comment by JonseyJones** [comment] 2024-01-21 15:17
>  @drunohazarb when you merge please add my save captcha thing.
 
+1 for that.

**Comment by drunohazarb** [comment] 2024-01-21 15:43
> here it is, tested on tampermonkey chrome/ff https://gist.github.com/aaafre4/55f8438e217a90a5ca5016fa6a75ae6b https://github.com/drunohazarb/4chan-captcha-solver/assets/156275726/4e05bcbb-e8b4-4f60-8f59-98a5fd125135

My only issue with this is that it relies on 4chan X to work. I'm going to add this to the script regardless but I'd appreciate it if you could get this to work without 4chan X.
As usual, I'm now testing the new model before pushing the update.

**Comment by aaafre4** [comment] 2024-01-21 15:46
Yeah I'll take a look tomorrow.

**Comment by aaafre5** [comment] 2024-01-21 16:43
wtf I can't see my own posts anymore so I made a new gh acc, anyway here is the updated version that works without 4chanx https://files.catbox.moe/aoldhp.js tested on ff with and without 4chanx, also added some checks if element exists just in case

**Comment by drunohazarb** [comment] 2024-01-21 17:39
Thank you, that works.

Now I'm just waiting for 4chan to serve me a few five-letter captchas, later this century hopefully...

**Comment by gir489returns** [comment] 2024-01-21 17:40
> wtf I can't see my own posts anymore so I made a new gh acc, anyway here is the updated version that works without 4chanx https://files.catbox.moe/aoldhp.js tested on ff with and without 4chanx, also added some checks if element exists just in case

This worked for me on the few I tried it on. Now we just need to wait for janny to do something for free to break it so we can create a counter move.

**Comment by drunohazarb** [comment] 2024-01-21 19:37
9be2254ba753c631a20d0382658ac04dceb9a947

**Closed by drunohazarb** 2024-01-21 19:37 UTC
