### ISSUE TITLE
They updated the captcha and now the script is broken

### ISSUE THREAD

**Issue by JonseyJones** [drunohazarb/4chan-captcha-solver#3] opened 2023-08-03 09:28 UTC
They updated the captcha, 08.01, and now the script is broken, the slider still works though.
It only guesses a bunch of letters here and there, never full results anymore.

**Comment by drunohazarb** [comment] 2023-08-03 17:56
Duplicate of #1

**Closed by drunohazarb** 2023-08-03 17:56 UTC
